baseURL = 'https://zhytou.github.io/'
languageCode = 'en-us'
title = 'Zhytou'
theme = 'vitae'
publishDir = 'docs'

copyright = "© Copyright [Zhytou](https://github.com/Zhytou)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
homepage = true
avatar = 'https://avatars.githubusercontent.com/u/56868292'
subtitle = 'May the force be with me.'
pagetitle = 'May the force be with me.'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/Zhytou"
